### ISSUE TITLE
add https://github.com/ricoberger/vault-secrets-operator to the list ? 

### ISSUE THREAD

**Issue by cristian-radu** [weaveworks/awesome-gitops#21]
I came across this young project a while ago and wanted to get some thoughts on adding it to our list 

Seems @ricoberger is a fan of GitOps :+1: 

One thing that comes to mind which might be debatable is that the actual secret itself is stored in Vault and git only holds a reference to that secret.

**Comment by stefanprodan** [comment]
I think it fits well with the GitOps model

**Comment by dimitropoulos** [comment]
Definitely!

**Comment by ricoberger** [comment]
Yeah he is^^. Thanks for adding.
