### ISSUE TITLE
Migrate from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by makkes** [weaveworks/awesome-gitops#49]
One less external system to care about.

**Comment by morancj** [comment]
We'd like to retire our CircleCI subscription this year.

**Comment by morancj** [comment]
There's no huge rush, as we have 6.8m pre-paid credits to use, and this is using ~6 / month. But it will fail when we terminate CircleCI.

**Comment by makkes** [comment]
There's a PR up now to get rid of CircleCI: #54
